data_dir: "./data"
logger:
  level: "debug"
  stdout: true
  file: ""
database:
  address: ["root@localhost:26257"]
  database: "layerg"
cluster:
  gossip_bindport: 7353
  members:
    - "localhost:7352"
socket:
  port: 8350
console:
  port: 8351