data_dir: "./data-node2"
logger:
  level: "debug"
  stdout: true
  file: ""
database:
  # address: ["root@localhost:26257"]
  address: ["postgresql://postgres:postgres@127.0.0.1:5433/layerg"]
  database: "layerg"
cluster:
  gossip_bindaddr: "0.0.0.0"
  gossip_bindport: 8354
  members: ["127.0.0.1:8353"]
  push_pull_interval: 60
  gossip_interval: 200
  tcp_timeout: 10
  probe_timeout: 500
  probe_interval: 1
  retransmit_mult: 2
  max_gossip_packet_size: 1400
  broadcast_queue_size: 128
  secret_key: "layerg-secret-key-32-bytes-long!"
  leader_election: true
socket:
  port: 8352
console:
  port: 8351
layerg_core:
  url: "https://agg-dev.layerg.xyz"
  hub_api_key: "syip1g6wd29f4tn8p78yc"
  hub_api_key_id: "f74c1b2e-33c0-4189-b639-f3162c84b13b"
  hub_url: "https://agg-dev.layerg.xyz/api"
  event_catcher_url: "https://event-gateway-dev.layerg.xyz"
redis_db:
  url: "localhost:6379" 