data_dir: "./data"
logger:
  level: "debug"
  stdout: true
  file: ""
database:
  address: ["root@localhost:26257"]
  database: "layerg"
# cluster:
#   gossip_bindport: 7353
#   members:
#     - "localhost:7352"
socket:
  port: 8350
console:
  port: 8351
layerg_core:
  url: "https://agg-dev.layerg.xyz"
  api_key: "syip1g6wd29f4tn8p78yc"
  api_key_id: "f74c1b2e-33c0-4189-b639-f3162c84b13b"