data_dir: "./data"
logger:
  level: "debug"
  stdout: true
  file: ""
database:
  # address: ["root@localhost:26257"]
  address: ["postgresql://postgres:postgres@127.0.0.1:5433/layerg"]
  database: "layerg"
cluster:
  gossip_bindport: 8353
  # membersưaocalhost:7353"
socket:
  port: 7350
console:
  port: 7351
layerg_core:
  url: "https://agg-dev.layerg.xyz"
  api_key: "syip1g6wd29f4tn8p78yc"
  api_key_id: "f74c1b2e-33c0-4189-b639-f3162c84b13b"
  portal_url: "https://agg-dev.layerg.xyz/api"
  event_catcher_url: "https://event-gateway-dev.layerg.xyz/"
redis_db:
  url: "localhost:6379"
