version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_DB=layerg
      - POSTGRES_PASSWORD=localdb
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - "8080"
      - "5432"
    ports:
      - "5432:5432"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "layerg"]
      interval: 3s
      timeout: 3s
      retries: 5
  layerg:
    container_name: layerg
    image: dangnp/arm64-layerg:latest
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          /layerg/layerg migrate up --database.address postgres:localdb@postgres:5432/layerg &&
          exec /layerg/layerg --name layerg1 --database.address postgres:localdb@postgres:5432/layerg --logger.level DEBUG --session.token_expiry_sec 7200
    restart: always
    links:
      - "postgres:db"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/layerg/data
    expose:
      - "7349"
      - "7350"
      - "7351"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "/layerg/layerg", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  data:
